### ISSUE TITLE
Proyecto 1 - Nuevo foro para dudas

### ISSUE THREAD

**Issue by PvasquezF** [PvasquezF/ArchivosPruebaOLC2#46]
Vamos a continuar por aqui, para el proyecto 2 se hará divisiones por categorías para que no sea tan complicado buscar.

**Comment by EddieAlvarez01** [comment]
Esperar el array asi esta permitido? str: Array<string> En el archivo de entrada recien añadido esta:
`function contains(str:string, strs:Array<string>):boolean{
    function imp(strs:Array<string>):boolean{
        if(strs.length == 0){
            return false;
        }
}`

No habian dicho que solo con los corchetes, "string[]"

**Comment by PvasquezF** [comment]
> Esperar el array asi esta permitido? str: Array En el archivo de entrada recien añadido esta:
> `function contains(str:string, strs:Array<string>):boolean{ function imp(strs:Array<string>):boolean{ if(strs.length == 0){ return false; } }`
> 
> No habian dicho que solo con los corchetes, "string[]"

Sí, debería ser string[]
Podes mandar un pull request con ese cambio para corregirlo.
