### ISSUE TITLE
Ejecución Ackermann

### ISSUE THREAD

**Issue by luisespino** [PvasquezF/ArchivosPruebaOLC2#51]
Buen día, tengo duda acerca de la ejecución de una parte de un archivo de prueba: console.log(ackermann(3, 7)); //1021

¿Qué pasa si la ejecución, por los parámetros que tiene, tarda un buen porcentaje del tiempo de calificación debido a los recursos limitados del navegador?

**Comment by PvasquezF** [comment]
Se tiene considerada la memoria, al ser web se puede ejecutar en otra pestaña y seguir evaluando en otra, pero si llega a dar problemas de memoria entonces se irá haciendo una reducción en los parámetros.
