### ISSUE TITLE
Dudas de proyecto 2 - Semana 1

### ISSUE THREAD

**Issue by PvasquezF** [PvasquezF/ArchivosPruebaOLC2#52]
Aqui se podran hacer consultas respecto al proyecto, cada semana se bloqueara y se iniciará uno nuevo para evitar la saturación de preguntas.

**Comment by echicasprado2** [comment]
![image](https://user-images.githubusercontent.com/43020046/95583251-10e6cd00-09f9-11eb-8455-882ed756a723.png)
La funcionalidad esta escrita al revés?

**Comment by echicasprado2** [comment]
![image](https://user-images.githubusercontent.com/43020046/95583634-aa15e380-09f9-11eb-8e26-0bfb1f9592a0.png)
Esto si se tomara en cuenta para el segundo proyecto? porque recuerdo que para el primero dijeron que los types solo guardarían tipos primitivos y otros types.

**Comment by echicasprado2** [comment]
![image](https://user-images.githubusercontent.com/43020046/95583785-e6e1da80-09f9-11eb-9f73-43ed745a3646.png)
Se, puede utilizar la traducción que se realizo en el proyecto 1?

**Comment by PvasquezF** [comment]
@EverChicas 

1. Si estan al reves, gracias por indicarlo. Se creo una nueva sección para tocar errores de redacción.

```
console.log("hoLa".toLowerCase());   // imprime hola
console.log("hoLa".toUpperCase());   // imprime HOLA
```

2. Los types pueden contener cualquier tipo de dato(number, boolean, string, type, array), e incluso pueden haber arrays de types.

3. La puedes utilizar si deseas, para este proyecto 2 no es necesario que se utilicen atributos heredados, pero si quieres reutilizar lo del proyecto 1 lo puedes hacer.

**Comment by wiicho57x** [comment]
Buenas noches una duda, el tema de las cadenas pueden ser con : "", '' y plantilla o solo comillas dobles ya que las plantillas creo que complicaria el manejo de cadena

**Comment by wiicho57x** [comment]
Buenas tengo una duda para la sintaxis de los areglos utilizando la nueva opciones de new array, ya que en typescript se puede de esta manera
let areglo : string []= new Array(1)  //se indica el tipo y el tamaño

error
let areglo : string [][] = new Array(1,2)  //aqui ya es un error ya que el metodo array solo soporta un parametro

por lo que me genera la duda si la opcion new array solo funcionaria para inicializar array de una demension

**Comment by echicasprado2** [comment]
Buenas tengo una duda como se van a declarar los arrays dentro de la definicion de un type? 
```javascript 
type node = {
id : number;
name : string;
value : number[];
value2 : number[][]
};
```
tiene que ser de esa forma? 

y al momento de estar declarando un type de ese tipo como seria la forma de hacerlo?
```javascript
let node = {
id:1,
name:"nuevo",
value: [1,2,3],
value2:[[1,2,3],[4,5,6]]
};

let node = {
id:1,
name:"nuevo",
value: new Array(3),
value2:new Array? 
};
```
para declarar arreglos de mas de una dimensión como seria la sintaxis?

**Comment by echicasprado2** [comment]
Para declarar arreglos se puede realizar de la forma:
```javascript
let arr:number[] = new Array(4);
let arr:number[] = [1,2,3,4];
let arr:number = new Array(4);
let arr:number = [1,2,3,4];
```

**Comment by WSantos35** [comment]
Una consulta:
Para los errores semánticos, como no va a existir una ejecución del código traducido de typescript como en el proyecto 1, solo se pueden reportar errores como una variable que no coincida con su valor con su tipo de dato algo como lo siguiente.

`let valores:string=5 //se reporte porque no coincide su tipo de dato`

pero errores como estos

`let nuevo:string[]=[1,2,3];
console.log(nuevo[6]);//Este error no se reporta en errores semánticos porque eso seria en ejecución de código`

al igual de acceder a un atributo type que no existe
`console.log(objeto_type.valor)//donde valor no existe este error no se reporte ya que también seria en ejecución`

No se si me pueden confirmar si se va a realizar de esa forma?

**Comment by javier3448** [comment]
Por si quieren insertar codigo en sus preguntas. Sirve un monton.
https://docs.github.com/es/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks

```typescript
console.log("Esto es codigo typescript :)");
```

**Comment by marckomatic** [comment]
Disculpen la pregunta. Como en typescript solo hay un tipo para numeros decimales y enteros, no se puede saber si se va a imprimir un decimal o un entero. Por esto, intente hacer una funcion en codigo de tres direcciones para ver si el numero era decimal o entero y asi poder distinguir entre printf de un numero entero y un decimal. Esto lo intente haciendo el modulo entre el numero y 1 asi:

t1 % 1;

Ya intente varias formas de hacer el modulo, pero no deja si utilizo un float, y si parseo el temporal entero pierdo la informacion para saber si el numero es decimal o entero.

Mi pregunta es si no importa si todos los numero se imprimen como floats? o si hay alguna otra solucion que puedan aportar los compañeros.

**Comment by marckomatic** [comment]
Buenas tardes, qusiera saber que tan factible es que cambiemos las variables del encabezado de C de float a double. Estaba viendo que los float no son tan exactos con numeros grandes, e incluso si declaras un numero grande directamente, algo como 

`float numero =152566.25465;`

Solamente los primeros dos decimales del numero son exactos, como el compilador de C no los reconoce bien. No se si para evitar conflictos a la hora de la calificacion podemos cambiar los tipos.

**Comment by erflod5** [comment]
@EverChicas201403532  @wiicho57x  
En la parte de arreglos le vamos a compartir una aclaración formal, solo vamos a platicar este tema con los ingenieros, lo mas probable es que se queden arreglos de una dimensión nada mas.

**Comment by erflod5** [comment]
@WSantos35 
1. Efectivamente el error de una posición afuera de rango no la podes reportar en tiempo de traducción.
2. El error del type si lo podes reportar en tiempo de traducción, al igual que errores como tipos de dato incompatibles, operaciones con tipos de dato no soportado, numero de parametros incorrecto, funciones no declaradas, variables no declaradas, entre otros.

**Comment by wiicho57x** [comment]
Buenas noches una consulta para los metodos y funciones es obligatorio que traigan tipo, no se infieren

**Comment by erflod5** [comment]
@wiicho57x 
Correcto compañero, al igual que las variables y constantes.

**Comment by erflod5** [comment]
@marckomatic 
Gracias por la observación compañero, lo vamos a tomar en cuenta y se los comunicamos.

**Comment by erflod5** [comment]
> Para declarar arreglos se puede realizar de la forma:
> 
> ```js
> let arr:number[] = new Array(4);
> let arr:number[] = [1,2,3,4];
> let arr:number = new Array(4);
> let arr:number = [1,2,3,4];
> ```

@EverChicas201403532 
La primera y la segunda forma si, la tercera y la cuarta sería un error de tipos.

**Comment by WSantos35** [comment]
Se puede realizar algo como esto para la instruccion new Array(index);?

``` typescript
let datos:number[]=new Array(4);

datos=new Array(2);

```

**Comment by echicasprado2** [comment]
```
int main(){
t0 = H;//Guardo el inicio de la variable en Heap
t1 = t0;//Copio el inicio de la en Heap, para moverme en las posiciones
Heap[(int)t1] = 104;//char -> h
t1 = t1 + 1;
Heap[(int)t1] = 111;//char -> o
t1 = t1 + 1;
Heap[(int)t1] = 108;//char -> l
t1 = t1 + 1;
Heap[(int)t1] = 97;//char -> a
t1 = t1 + 1;
Heap[(int)t1] = -1;//fin de cadena
```
es valido que pueda usar el casteo para acceder a las posiciones de stack o heap? esto por el motivo que los temporales son float.

**Comment by javier3448** [comment]
Todavia tenemos que hacer los template string?

**Comment by erflod5** [comment]
> ```
> int main(){
> t0 = H;//Guardo el inicio de la variable en Heap
> t1 = t0;//Copio el inicio de la en Heap, para moverme en las posiciones
> Heap[(int)t1] = 104;//char -> h
> t1 = t1 + 1;
> Heap[(int)t1] = 111;//char -> o
> t1 = t1 + 1;
> Heap[(int)t1] = 108;//char -> l
> t1 = t1 + 1;
> Heap[(int)t1] = 97;//char -> a
> t1 = t1 + 1;
> Heap[(int)t1] = -1;//fin de cadena
> ```
> 
> es valido que pueda usar el casteo para acceder a las posiciones de stack o heap? esto por el motivo que los temporales son float.

@EverChicas201403532 
Si es valido y es la forma correcta

**Comment by erflod5** [comment]
> Todavia tenemos que hacer los template string?

No

**Comment by itzmarfranco** [comment]
No me queda claro cómo se debe almacenar la información en la pila y el montículo. ¿Podrían dar un ejemplo práctico de cómo quedaría el código traducido? Gracias.

**Comment by wygd-usac** [comment]
Que tal, si vamos a utilizar algunas funciones nativas en nuestro codigo generado, por ejemplo digamos que quiero hacer una para imprimir un caracter:
``` c
int posicion_caracter = 0;
imprimirCaracter(){
printf("%c",heap[posicion_caracter]);
}
// llamada
posicion_caracter = (int) stack[p];
imprimirCaracter();
```
Puedo declarar sus parametros de esa forma, usando variables con un nombre como "posicion_caracter" o en esas funciones tambien es necesario hacer uso de temporales, por ejemplo definir que el temporal t0 siempre va a ser el parametro de entrada para la rutina imprimirCaracter();

``` c
//el parámetro con el indice del carácter a imprimir siempre va a ser t0
imprimirCaracter(){
printf("%c",heap[t0]);
}
// llamada
t0 = (int) stack[p];
imprimirCaracter();
```
Obviamente las funciones reales serian mas complejas, ya que un solo carácter se puede imprimir directamente, esa es solo para ejemplificar.

**Comment by racarlosdavid** [comment]
en la operacion suma que valor toma boolea ? siempre 1 y 0 si se opera con number y true y false si se opera con string 
por ejemplo:
5 + true = 6 -> true se maneja como number
5 + true = "5true" -> true se maneja como string
"hola" + true = "holatrue" -> true se maneja como string
"hola" + true = "hola1" -> true se maneja como number

**Comment by erflod5** [comment]
> en la operacion suma que valor toma boolea ? siempre 1 y 0 si se opera con number y true y false si se opera con string
> por ejemplo:
> 5 + true = 6 -> true se maneja como number
> 5 + true = "5true" -> true se maneja como string
> "hola" + true = "holatrue" -> true se maneja como string
> "hola" + true = "hola1" -> true se maneja como number

@racarlosdavid 
5 + true = 6
"Hola" + true = "Holatrue"

**Comment by erflod5** [comment]
> Que tal, si vamos a utilizar algunas funciones nativas en nuestro codigo generado, por ejemplo digamos que quiero hacer una para imprimir un caracter:
> 
> ```c
> int posicion_caracter = 0;
> imprimirCaracter(){
> printf("%c",heap[posicion_caracter]);
> }
> // llamada
> posicion_caracter = (int) stack[p];
> imprimirCaracter();
> ```
> 
> Puedo declarar sus parametros de esa forma, usando variables con un nombre como "posicion_caracter" o en esas funciones tambien es necesario hacer uso de temporales, por ejemplo definir que el temporal t0 siempre va a ser el parametro de entrada para la rutina imprimirCaracter();
> 
> ```c
> //el parámetro con el indice del carácter a imprimir siempre va a ser t0
> imprimirCaracter(){
> printf("%c",heap[t0]);
> }
> // llamada
> t0 = (int) stack[p];
> imprimirCaracter();
> ```
> 
> Obviamente las funciones reales serian mas complejas, ya que un solo carácter se puede imprimir directamente, esa es solo para ejemplificar.

@wygd-usac 
Usa temporales para ese caso, podes definir una serie de temporales reservados específicamente para tus funciones nativas.

**Comment by itzmarfranco** [comment]
Alguien que ya haya empezado a traducir que me quiera echar una manita. Solo no entiendo cómo se almacena la información en en el heap y stack. Gracias.

**Comment by WSantos35** [comment]
Para el operador potencia de typescript al pasarlo a C se puede usar la funcion pow(); de math.h
ya que algo como lo siguiente me da un resultado erroneo.

``` c
/******************************************************************************

                            Online C Compiler.
                Code, Compile, Run and Debug C program online.
Write your code in this editor and press "Run" button to compile and execute it.

*******************************************************************************/

#include <stdio.h>

float t1,t2,t3;
int main()
{
    t1=2;
    t2=2;
    t3=(int)t1^(int)t2;
    printf("%d",(int)t3);

    return 0;
}

```

**Comment by itzmarfranco** [comment]
> Para el operador potencia de typescript al pasarlo a C se puede usar la funcion pow(); de math.h
> ya que algo como lo siguiente me da un resultado erroneo.
> 
> ```c
> /******************************************************************************
> 
>                             Online C Compiler.
>                 Code, Compile, Run and Debug C program online.
> Write your code in this editor and press "Run" button to compile and execute it.
> 
> *******************************************************************************/
> 
> #include <stdio.h>
> 
> float t1,t2,t3;
> int main()
> {
>     t1=2;
>     t2=2;
>     t3=(int)t1^(int)t2;
>     printf("%d",(int)t3);
> 
>     return 0;
> }
> ```

Recuerdo que lo que dijeron era que debías incluir funciones "nativas" en tu código de C que te manejaran esas operaciones. 
Algo como 

```
float potenciar(){
     ...
     return;
}
```

Y solo la mandás a llamar cuando la necesités.

**Comment by pablorocad** [comment]
Para la operación modulo (numero % numero) podemos usar casteo cuando se opera con temporales? ya que este solo acepta INT

ejemplo de como quedaria:
```
t2 = 5 % (int)t1;
```

**Comment by marckomatic** [comment]
Buenas tardes, disculpen, tengo una con las pasadas en el compilador:

Si tengo, por ejemplo:

`
function a():int{
     function b():int{
           let variable2:number = variable1; // uso de una variable aun no declarada
           return variable2 + 1;
     }
     let variable3:number = b(); //llamada a funcion anidada. 
     let variable1:number = 65;

}
`
Quisiera saber si se tienen que hacer varias pasadas en la traduccion, porque hay algunos momentos, por ejemplo en la declaracion de la variable 3 en donde se llama a b(), pero variable1 no esta declarada. 

Por otro lado, si traduzco las declaraciones de funciones al principio, antes de que se ejecuten las declaraciones de variables, la traduccion me tiraria un error diciendo que variable2 no ha sido inicializada.

**Comment by racarlosdavid** [comment]
buenas tengo duda de como va a funcionar la función main:
en el código de alto nivel va a venir una función main por ejemplo

CODIGO ALTO NIVEL:

function suma(a:number,b:number):number{
   return a +b;
}

function main ():void{
   suma(5,5);
}

TRADUCCION :

//AQUI EL ENCABEZADO

void main(){
   //Paso de parametros
   suma();
}

void suma(){
   //instrucciones
  return;
}

o el main no va a venir en el código de alto nivel

CODIGO ALTO NIVEL:

function suma(a:number,b:number):number{
   return a +b;
}

suma(5,5);

y tendría que agregarle el main desde mi generación de código ??

**Comment by itzmarfranco** [comment]
> buenas tengo duda de como va a funcionar la función main:
> en el código de alto nivel va a venir una función main por ejemplo
> 
> CODIGO ALTO NIVEL:
> 
> function suma(a:number,b:number):number{
> return a +b;
> }
> 
> function main ():void{
> suma(5,5);
> }
> 
> TRADUCCION :
> 
> //AQUI EL ENCABEZADO
> 
> void main(){
> //Paso de parametros
> suma();
> }
> 
> void suma(){
> //instrucciones
> return;
> }
> 
> o el main no va a venir en el código de alto nivel
> 
> CODIGO ALTO NIVEL:
> 
> function suma(a:number,b:number):number{
> return a +b;
> }
> 
> suma(5,5);
> 
> y tendría que agregarle el main desde mi generación de código ??

El main no viene explícito en el código de alto nivel.

**Comment by Davis-Edward-201700972** [comment]
printf("%d\n",(int)t1); , Se puede poner **\n** en el printf para el salto de linea?

**Comment by itzmarfranco** [comment]
Buena noche. ¿Está correcto así el resultado de los tipos?

![Capture](https://user-images.githubusercontent.com/6559172/96534512-1d66f300-124d-11eb-9e1a-c56982eb24f6.PNG)

**Comment by erflod5** [comment]
> Para la operación modulo (numero % numero) podemos usar casteo cuando se opera con temporales? ya que este solo acepta INT

@pablorocad 
Si pueden usarla

**Comment by erflod5** [comment]
> Buenas tardes, disculpen, tengo una con las pasadas en el compilador:
> 
> Si tengo, por ejemplo:
> 
> `
> function a():int{
> function b():int{
> let variable2:number = variable1; // uso de una variable aun no declarada
> return variable2 + 1;
> }
> let variable3:number = b(); //llamada a funcion anidada.
> let variable1:number = 65;
> 
> }
> `
> Quisiera saber si se tienen que hacer varias pasadas en la traduccion, porque hay algunos momentos, por ejemplo en la declaracion de la variable 3 en donde se llama a b(), pero variable1 no esta declarada.
> 
> Por otro lado, si traduzco las declaraciones de funciones al principio, antes de que se ejecuten las declaraciones de variables, la traduccion me tiraria un error diciendo que variable2 no ha sido inicializada.

@marckomatic 
Si, tendrias que hacer varias pasadas

**Comment by erflod5** [comment]
> buenas tengo duda de como va a funcionar la función main:
> en el código de alto nivel va a venir una función main por ejemplo
> 
> CODIGO ALTO NIVEL:
> 
> function suma(a:number,b:number):number{
> return a +b;
> }
> 
> function main ():void{
> suma(5,5);
> }
> 
> TRADUCCION :
> 
> //AQUI EL ENCABEZADO
> 
> void main(){
> //Paso de parametros
> suma();
> }
> 
> void suma(){
> //instrucciones
> return;
> }
> 
> o el main no va a venir en el código de alto nivel
> 
> CODIGO ALTO NIVEL:
> 
> function suma(a:number,b:number):number{
> return a +b;
> }
> 
> suma(5,5);
> 
> y tendría que agregarle el main desde mi generación de código ??

@racarlosdavid 
El main no viene el alto nivel, este va del lado de C ya que representa el punto de inicio de tu programa

**Comment by erflod5** [comment]
> printf("%d\n",(int)t1); , Se puede poner **\n** en el printf para el salto de linea?

@Davis-Edward-201700972 para que pondrías el salto de linea?

**Comment by erflod5** [comment]
> Buena noche. ¿Está correcto así el resultado de los tipos?
> 
> ![Capture](https://user-images.githubusercontent.com/6559172/96534512-1d66f300-124d-11eb-9e1a-c56982eb24f6.PNG)

'dos' + false = 'dosfalse'

Las demás están bien.

**Comment by erflod5** [comment]
> Se puede realizar algo como esto para la instruccion new Array(index);?
> 
> ```ts
> let datos:number[]=new Array(4);
> 
> datos=new Array(2);
> ```

@WSantos35 SI se puede

**Comment by Davis-Edward-201700972** [comment]
> > printf("%d\n",(int)t1); , Se puede poner **\n** en el printf para el salto de linea?
> 
> @Davis-Edward-201700972 para que pondrías el salto de linea?

si imprimo 2 numeros, para que no salgan pegados por ejemplo: console.log(13);  console.log(56); y que se imprima: 1356 en vez de
13
56

**Comment by erflod5** [comment]
+@Davis-Edward-201700972 
Ah ya entiendo, podes agregarle un printf de un salto de linea despues de cada console.log para tener un mejor orden

console.log(1+2+3);

t0 = 1 + 2;
t1 = t0 + 3;
printf("%f", (float)t1);
printf("\n");

**Comment by Davis-Edward-201700972** [comment]
> +@Davis-Edward-201700972
> Ah ya entiendo, podes agregarle un printf de un salto de linea despues de cada console.log para tener un mejor orden
> 
> console.log(1+2+3);
> 
> t0 = 1 + 2;
> t1 = t0 + 3;
> printf("%f", (float)t1);
> printf("\n");

Gracias

**Comment by marckomatic** [comment]
Buenas tardes, disculpen los operadores de asignacion +=, -=, *=, **= y los otros se tienen que incluir?

**Comment by erflod5** [comment]
@marckomatic
No

Nota: pone tus nuevas dudas en los issues abiertos, este ya está cerrado
