### ISSUE TITLE
Dudas de cosas que se pueden o no en el proyecto.

### ISSUE THREAD

**Issue by PvasquezF** [PvasquezF/ArchivosPruebaOLC2#53]
Aqui pueden poner sus dudas de lo que puede o no hacer el proyecto.
Ejemplo:

¿Puedo hacer accesos a arreglo con valores booleanos?

```
const a = [1,2,3,4];
console.log(a[true]);
```
R. No, no es permitido.

**Comment by CristianFrancisco85** [comment]
¿El acceso a array siempre es explicito? 

Ej.
let a:string[]=["Hola","Mundo",":)"];
let b:number=(2+2/2)-1;  // 1

//Este acceso es facil de traducir con la tabla se simbolos
let c:number=a[1];

//Este acceso no, ya que no se tiene el valor de b y una formula para mapeo lexicografico en arrays de strings tampoco se puede hacer en traduccion ya que si un string del arreglo cambia se perderia el orden
let c:number=a[b];

**Comment by erflod5** [comment]
> ¿El acceso a array siempre es explicito?
> 
> Ej.
> let a:string[]=["Hola","Mundo",":)"];
> let b:number=(2+2/2)-1; // 1
> 
> //Este acceso es facil de traducir con la tabla se simbolos
> let c:number=a[1];
> 
> //Este acceso no, ya que no se tiene el valor de b y una formula para mapeo lexicografico en arrays de strings tampoco se puede hacer en traduccion ya que si un string del arreglo cambia se perderia el orden
> let c:number=a[b];

@CristianFrancisco85 
No tenes el valor de b en tiempo de compilacion, pero si sabes la metadata de esa variable como
- tipo
- si es global o local
- si es una constante
- direccion de memoria de la variable

Por lo tanto, cuando haces ese acceso lo que haces en generar el codigo intermedio en donde accedes a esa variable y obtener el valor del arreglo en la posición ya definida. Para esto haces el uso de temporales, accesos al stack, etc.

En este proyecto NO TIENEN QUE EJECUTAR CODIGO, solo traducir a código intermedio.

**Comment by EddieAlvarez01** [comment]
Puedo castear en 3D asi, solo para obtener algo mas preciso:
t1 = (int)(t2/t15) o esto:
t2 = (int) t3

**Comment by erflod5** [comment]
> Puedo castear en 3D asi, solo para obtener algo mas preciso:
> t1 = (int)(t2/t15) o esto:
> t2 = (int) t3
@EddieAlvarez01 
Cual es el fin del uso de esas instrucciones?

**Comment by EddieAlvarez01** [comment]
> > Puedo castear en 3D asi, solo para obtener algo mas preciso:
> > t1 = (int)(t2/t15) o esto:
> > t2 = (int) t3
> > @EddieAlvarez01
> > Cual es el fin del uso de esas instrucciones?

Solo la utilizo para separar la parte entera de la decimal y poder concatenar decimales mas facilmente

**Comment by erflod5** [comment]
> > > Puedo castear en 3D asi, solo para obtener algo mas preciso:
> > > t1 = (int)(t2/t15) o esto:
> > > t2 = (int) t3
> > > @EddieAlvarez01
> > > Cual es el fin del uso de esas instrucciones?
> 
> Solo la utilizo para separar la parte entera de la decimal y poder concatenar decimales mas facilmente

@EddieAlvarez01 
Si, está bien

**Comment by bchacon45** [comment]
¿Puedo castear los números de esta forma al insertarlos directamente en una operación?
t6 = (double)42/(double)8;

**Comment by erflod5** [comment]
> ¿Puedo castear los números de esta forma al insertarlos directamente en una operación?
> t6 = (double)42/(double)8;

@bchacon45 
No
